### ISSUE TITLE
Publish to Chrome Extensions Store

### ISSUE THREAD

**Issue by cloudlena** [JosephBuchma/Go-Present-code-highlighter#2]
Chrome doesn't let you enable extensions which aren't part of the extensions store anymore... Can you please publish his extension to the store?

**Comment by josephbuchma** [comment]
@mastertinner [store](https://chrome.google.com/webstore/detail/go-present-code-highlight/depioieabmbifhmkflcagceedklkiahb)
Also added options page and popup with color scheme selector.

**Comment by cloudlena** [comment]
That's awesome! Thanks, @josephbuchma!
